# Pull Network from Aesthetics Wiki
we now use cloudscraper

In [1]:
# 1. Web Scraping & HTTP Requests
import requests
import cloudscraper
from bs4 import BeautifulSoup

# 2. Data Manipulation & Processing
import re
import ast
import itertools
import numpy as np
import pandas as pd

# 3. Network Analysis & Graph Theory
import networkx as nx

# 4. Data Visualization
import matplotlib.pyplot as plt

# 5. Core Utilities (Time & Randomness)
import time
import random

/Users/louischonksterlaptop/Python/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# Test URL

In [2]:
url = "https://aesthetics.fandom.com/wiki/List_of_Aesthetics"

# Create a cloudscraper instance (mimics real browser engines)
scraper = cloudscraper.create_scraper()

# Use the scraper instead of requests.get
response = scraper.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Target the primary wiki body content block
    content_div = soup.find('div', class_='mw-parser-output')
    
    if content_div:
        links = content_div.find_all('a', href=True)
        for link in links:
            href = link['href']
            if href.startswith("/wiki/") and not any(x in href for x in [":", "Main_Page", "List_of_"]):
                print(f"{link.text.strip()}: https://aesthetics.fandom.com{href}")
    else:
        print("Connected successfully, but couldn't find the content block.")
else:
    print(f"Cloudscraper was also blocked. Status code: {response.status_code}")

Rococo: https://aesthetics.fandom.com/wiki/Rococo
Urbancore: https://aesthetics.fandom.com/wiki/Urbancore
Minimalism: https://aesthetics.fandom.com/wiki/Minimalism
Aesthetic Visual Index: https://aesthetics.fandom.com/wiki/Aesthetic_Visual_Index
Find Aesthetic by Image: https://aesthetics.fandom.com/wiki/Find_Aesthetic_by_Image
Vaporwave: https://aesthetics.fandom.com/wiki/Vaporwave
Cottagecore: https://aesthetics.fandom.com/wiki/Cottagecore
Techwear: https://aesthetics.fandom.com/wiki/Techwear
Lolita: https://aesthetics.fandom.com/wiki/Lolita
Goth: https://aesthetics.fandom.com/wiki/Goth
Punk: https://aesthetics.fandom.com/wiki/Punk
Baroque: https://aesthetics.fandom.com/wiki/Baroque
Victorian: https://aesthetics.fandom.com/wiki/Victorian
Cyberpunk: https://aesthetics.fandom.com/wiki/Cyberpunk
Dungeon Synth: https://aesthetics.fandom.com/wiki/Dungeon_Synth
By Category: https://aesthetics.fandom.com/wiki/By_Category
By Decade: https://aesthetics.fandom.com/wiki/By_Decade
Wanted Pages: https://aesthetics.fandom.com/wiki/Wanted_Pages
2014 Tumblr: https://aesthetics.fandom.com/wiki/2014_Tumblr
Alternative: https://aesthetics.fandom.com/wiki/Alternative
Americana: https://aesthetics.fandom.com/wiki/Americana
Coquette: https://aesthetics.fandom.com/wiki/Coquette
Dark Culture: https://aesthetics.fandom.com/wiki/Dark_Culture
Early 2020s TikTok: https://aesthetics.fandom.com/wiki/Early_2020s_TikTok
Early Web 2.0 Nostalgia: https://aesthetics.fandom.com/wiki/Early_Web_2.0_Nostalgia
Eurotrash: https://aesthetics.fandom.com/wiki/Eurotrash
Glitter Graphics: https://aesthetics.fandom.com/wiki/Glitter_Graphics
Hyperpop: https://aesthetics.fandom.com/wiki/Hyperpop
Punk Derivatives: https://aesthetics.fandom.com/wiki/Punk_Derivatives
Regional Gothic: https://aesthetics.fandom.com/wiki/Regional_Gothic
SoundCloud Rap: https://aesthetics.fandom.com/wiki/SoundCloud_Rap
Y2K: https://aesthetics.fandom.com/wiki/Y2K
2 Tone: https://aesthetics.fandom.com/wiki/2_Tone
2000s Modern Baroque: https://aesthetics.fandom.com/wiki/2000s_Modern_Baroque
2000s Preppy: https://aesthetics.fandom.com/wiki/2000s_Preppy
2000s Yoga Mom: https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom
2010s Bright Kawaii: https://aesthetics.fandom.com/wiki/2010s_Bright_Kawaii
2010s Dark Fandom: https://aesthetics.fandom.com/wiki/2010s_Dark_Fandom
2010s Meme Maximalism: https://aesthetics.fandom.com/wiki/2010s_Meme_Maximalism
2010s Soft Kawaii: https://aesthetics.fandom.com/wiki/2010s_Soft_Kawaii
2010s Summer Nostalgia: https://aesthetics.fandom.com/wiki/2010s_Summer_Nostalgia
2014 Girly: https://aesthetics.fandom.com/wiki/2014_Girly
2020 Alt: https://aesthetics.fandom.com/wiki/2020_Alt
2020s Preppy: https://aesthetics.fandom.com/wiki/2020s_Preppy
50s Suburbia: https://aesthetics.fandom.com/wiki/50s_Suburbia
8-Bit: https://aesthetics.fandom.com/wiki/8-Bit
80s Workout: https://aesthetics.fandom.com/wiki/80s_Workout
90s Cool: https://aesthetics.fandom.com/wiki/90s_Cool
Abstract Tech: https://aesthetics.fandom.com/wiki/Abstract_Tech
Acid Design: https://aesthetics.fandom.com/wiki/Acid_Design
Acid House: https://aesthetics.fandom.com/wiki/Acid_House
Acubi: https://aesthetics.fandom.com/wiki/Acubi
Adventurecore: https://aesthetics.fandom.com/wiki/Adventurecore
Adventure Pulp: https://aesthetics.fandom.com/wiki/Adventure_Pulp
Aestheticism: https://aesthetics.fandom.com/wiki/Aestheticism
Aesthetic Rap: https://aesthetics.fandom.com/wiki/Aesthetic_Rap
Aetherpunk: https://aesthetics.fandom.com/wiki/Aetherpunk
Afrofuturism: https://aesthetics.fandom.com/wiki/Afrofuturism
Afropunk: https://aesthetics.fandom.com/wiki/Afropunk
After Hours: https://aesthetics.fandom.com/wiki/After_Hours
Agejo: https://aesthetics.fandom.com/wiki/Agejo
Aggrotech: https://aesthetics.fandom.com/wiki/Aggrotech
Ah Beng: https://aesthetics.fandom.com/wiki/Ah_Beng
Akibapop: https://aesthetics.fandom.com/wiki/Akibapop
Aliencore: https://aesthetics.fandom.com/wiki/Aliencore
Aliyahcore: https://aesthetics.fandom.com/wiki/Aliyahcore
Amekaji: https://aesthetics.fandom.com/wiki/Amekaji
American Kitsch: https://aesthetics.fandom.com/wiki/American_Kitsch
American Pioneers: https://aesthetics.fandom.com/wiki/American_Pioneers
American Thanksgiving: https://aesthetics.fandom.com/wiki/American_Thanksgiving
Analog Horror: https://aesthetics.fandom.com/wiki/Analog_Horror
Anarcho-Punk: https://aesthetics.fandom.com/wiki/Anarcho-Punk
Ancient Egypt: https://aesthetics.fandom.com/wiki/Ancient_Egypt
Androgynous: https://aesthetics.fandom.com/wiki/Androgynous
Angelcore: https://aesthetics.fandom.com/wiki/Angelcore
Anglo Gothic: https://aesthetics.fandom.com/wiki/Anglo_Gothic
Angura Kei: https://aesthetics.fandom.com/wiki/Angura_Kei
Animecore: https://aesthetics.fandom.com/wiki/Animecore
Antwerp Six: https://aesthetics.fandom.com/wiki/Antwerp_Six
Appalachian Gothic: https://aesthetics.fandom.com/wiki/Appalachian_Gothic
Après-ski: https://aesthetics.fandom.com/wiki/Apr%C3%A8s-ski
Arabian Nights: https://aesthetics.fandom.com/wiki/Arabian_Nights
Arabfunny: https://aesthetics.fandom.com/wiki/Arabfunny
Arcadecore: https://aesthetics.fandom.com/wiki/Arcadecore
Aristocrat: https://aesthetics.fandom.com/wiki/Aristocrat
Art Academia: https://aesthetics.fandom.com/wiki/Art_Academia
Artcore: https://aesthetics.fandom.com/wiki/Artcore
Art Deco: https://aesthetics.fandom.com/wiki/Art_Deco
Arte Povera: https://aesthetics.fandom.com/wiki/Arte_Povera
Art Hoe: https://aesthetics.fandom.com/wiki/Art_Hoe
Art Nouveau: https://aesthetics.fandom.com/wiki/Art_Nouveau
Arts and Crafts: https://aesthetics.fandom.com/wiki/Arts_and_Crafts
Art Singulier: https://aesthetics.fandom.com/wiki/Art_Singulier
Asian Baby Girl: https://aesthetics.fandom.com/wiki/Asian_Baby_Girl
Atomic Age: https://aesthetics.fandom.com/wiki/Atomic_Age
Atompunk: https://aesthetics.fandom.com/wiki/Atompunk
Auroracore: https://aesthetics.fandom.com/wiki/Auroracore
Australiana: https://aesthetics.fandom.com/wiki/Australiana
Autumn Aesthetic: https://aesthetics.fandom.com/wiki/Autumn_Aesthetic
Avant Apocalypse: https://aesthetics.fandom.com/wiki/Avant_Apocalypse
Avant Basic: https://aesthetics.fandom.com/wiki/Avant_Basic
Avantropop: https://aesthetics.fandom.com/wiki/Avantropop
Babycore: https://aesthetics.fandom.com/wiki/Babycore
Babygirl: https://aesthetics.fandom.com/wiki/Babygirl
Baddie: https://aesthetics.fandom.com/wiki/Baddie
Bakala: https://aesthetics.fandom.com/wiki/Bakala
Balearic Aesthetic: https://aesthetics.fandom.com/wiki/Balearic_Aesthetic
Ballet: https://aesthetics.fandom.com/wiki/Ballet
Balletcore: https://aesthetics.fandom.com/wiki/Balletcore
Ballroom Culture: https://aesthetics.fandom.com/wiki/Ballroom_Culture
Bankara: https://aesthetics.fandom.com/wiki/Bankara
Barber Beats: https://aesthetics.fandom.com/wiki/Barber_Beats
Barbiecore: https://aesthetics.fandom.com/wiki/Barbiecore
Bardcore: https://aesthetics.fandom.com/wiki/Bardcore
Baroque: https://aesthetics.fandom.com/wiki/Baroque
Basque Radical Rock: https://aesthetics.fandom.com/wiki/Basque_Radical_Rock
Bastardcore: https://aesthetics.fandom.com/wiki/Bastardcore
Bauhaus: https://aesthetics.fandom.com/wiki/Bauhaus
B-Boy: https://aesthetics.fandom.com/wiki/B-Boy
Beach Goth: https://aesthetics.fandom.com/wiki/Beach_Goth
Beatnik: https://aesthetics.fandom.com/wiki/Beatnik
Belgian Popcorn: https://aesthetics.fandom.com/wiki/Belgian_Popcorn
Berlin Techno Fashion: https://aesthetics.fandom.com/wiki/Berlin_Techno_Fashion
Biedermeier: https://aesthetics.fandom.com/wiki/Biedermeier
Biker: https://aesthetics.fandom.com/wiki/Biker
Bills: https://aesthetics.fandom.com/wiki/Bills_(Congolese_subculture)
Bimbocore: https://aesthetics.fandom.com/wiki/Bimbocore
Biopunk: https://aesthetics.fandom.com/wiki/Biopunk
Black Ivy: https://aesthetics.fandom.com/wiki/Black_Ivy
Black Metal: https://aesthetics.fandom.com/wiki/Black_Metal
Blob World: https://aesthetics.fandom.com/wiki/Blob_World
Bloghouse: https://aesthetics.fandom.com/wiki/Bloghouse
Blogspot Scene: https://aesthetics.fandom.com/wiki/Blogspot_Scene
Blokecore: https://aesthetics.fandom.com/wiki/Blokecore
Blokette: https://aesthetics.fandom.com/wiki/Blokette
Bloomcore: https://aesthetics.fandom.com/wiki/Bloomcore
Blueberry Girl: https://aesthetics.fandom.com/wiki/Blueberry_Girl
B-Movie Horror: https://aesthetics.fandom.com/wiki/B-Movie_Horror
Bobby-Soxer: https://aesthetics.fandom.com/wiki/Bobby-Soxer
Bodikon: https://aesthetics.fandom.com/wiki/Bodikon
Bogan: https://aesthetics.fandom.com/wiki/Bogan
Bohemian: https://aesthetics.fandom.com/wiki/Bohemian
Boho-Chic: https://aesthetics.fandom.com/wiki/Boho-Chic
Bombardier: https://aesthetics.fandom.com/wiki/Bombardier
Bon Chic, Bon Genre: https://aesthetics.fandom.com/wiki/Bon_Chic,_Bon_Genre
Bondage: https://aesthetics.fandom.com/wiki/Bondage
Bosozoku: https://aesthetics.fandom.com/wiki/Bosozoku
Botswana Metalheads: https://aesthetics.fandom.com/wiki/Botswana_Metalheads
Boujee: https://aesthetics.fandom.com/wiki/Boujee
Brat Summer: https://aesthetics.fandom.com/wiki/Brat_Summer
Bravú: https://aesthetics.fandom.com/wiki/Brav%C3%BA
Brazilcore: https://aesthetics.fandom.com/wiki/Brazilcore
Brazilian Bombshell: https://aesthetics.fandom.com/wiki/Brazilian_Bombshell
Brazilian Carnival: https://aesthetics.fandom.com/wiki/Brazilian_Carnival
Brazilian Phonk: https://aesthetics.fandom.com/wiki/Brazilian_Phonk
Bright Tertiaries: https://aesthetics.fandom.com/wiki/Bright_Tertiaries
Britpop: https://aesthetics.fandom.com/wiki/Britpop
British Countryside: https://aesthetics.fandom.com/wiki/British_Countryside
Bro Culture: https://aesthetics.fandom.com/wiki/Bro_Culture
Bro Hoe: https://aesthetics.fandom.com/wiki/Bro_Hoe
Bronze Age China: https://aesthetics.fandom.com/wiki/Bronze_Age_China
Brostep: https://aesthetics.fandom.com/wiki/Brostep
Brutalism: https://aesthetics.fandom.com/wiki/Brutalism
Bubble Bujo: https://aesthetics.fandom.com/wiki/Bubble_Bujo
Bubbleglam: https://aesthetics.fandom.com/wiki/Bubbleglam
Bubblegum Bitch: https://aesthetics.fandom.com/wiki/Bubblegum_Bitch
Bubblegum Bling: https://aesthetics.fandom.com/wiki/Bubblegum_Bling
Bubblegum Coquette: https://aesthetics.fandom.com/wiki/Bubblegum_Coquette
Bubblegum Dance: https://aesthetics.fandom.com/wiki/Bubblegum_Dance
Buchón: https://aesthetics.fandom.com/wiki/Buch%C3%B3n
Buckle Bunny: https://aesthetics.fandom.com/wiki/Buckle_Bunny
Buffalo Style: https://aesthetics.fandom.com/wiki/Buffalo_Style
Burlesque: https://aesthetics.fandom.com/wiki/Burlesque
Business Casual: https://aesthetics.fandom.com/wiki/Business_Casual
Business Formal: https://aesthetics.fandom.com/wiki/Business_Formal
Business Professional: https://aesthetics.fandom.com/wiki/Business_Professional
Busukawaii: https://aesthetics.fandom.com/wiki/Busukawaii
Byzantine: https://aesthetics.fandom.com/wiki/Byzantine
Cabincore: https://aesthetics.fandom.com/wiki/Cabincore
Cacareco Girl: https://aesthetics.fandom.com/wiki/Cacareco_Girl
Cagole: https://aesthetics.fandom.com/wiki/Cagole
Campcore: https://aesthetics.fandom.com/wiki/Campcore
Candycore: https://aesthetics.fandom.com/wiki/Candycore
Candyland: https://aesthetics.fandom.com/wiki/Candyland
Cani: https://aesthetics.fandom.com/wiki/Cani
Cannibalcore: https://aesthetics.fandom.com/wiki/Cannibalcore
Caricaturism: https://aesthetics.fandom.com/wiki/Caricaturism
Carson-Dellosa Art Style: https://aesthetics.fandom.com/wiki/Carson-Dellosa_Art_Style
Casino: https://aesthetics.fandom.com/wiki/Casino
Cassette Futurism: https://aesthetics.fandom.com/wiki/Cassette_Futurism
Casuals: https://aesthetics.fandom.com/wiki/Casuals
Catholic Horror: https://aesthetics.fandom.com/wiki/Catholic_Horror
Catholic Kitsch: https://aesthetics.fandom.com/wiki/Catholic_Kitsch
Catholic Mexican Girl: https://aesthetics.fandom.com/wiki/Catholic_Mexican_Girl
Cayetana: https://aesthetics.fandom.com/wiki/Cayetana
Celtic Revival: https://aesthetics.fandom.com/wiki/Celtic_Revival
Changelingcore: https://aesthetics.fandom.com/wiki/Changelingcore
Chaotic Academia: https://aesthetics.fandom.com/wiki/Chaotic_Academia
Chav: https://aesthetics.fandom.com/wiki/Chav
Chernobyl Stalkers: https://aesthetics.fandom.com/wiki/Chernobyl_Stalkers
Cherry Emoji Twitter: https://aesthetics.fandom.com/wiki/Cherry_Emoji_Twitter
Chicago Drill: https://aesthetics.fandom.com/wiki/Chicago_Drill
Chicha: https://aesthetics.fandom.com/wiki/Chicha
Chic Modernist: https://aesthetics.fandom.com/wiki/Chic_Modernist
Chinese Folk Horror: https://aesthetics.fandom.com/wiki/Chinese_Folk_Horror
Chinese Dreamcore: https://aesthetics.fandom.com/wiki/Chinese_Dreamcore
Chinese New Year: https://aesthetics.fandom.com/wiki/Chinese_New_Year
Chinoiserie: https://aesthetics.fandom.com/wiki/Chinoiserie
Choco Girl: https://aesthetics.fandom.com/wiki/Choco_Girl
Cholo: https://aesthetics.fandom.com/wiki/Cholo
Cholombiano: https://aesthetics.fandom.com/wiki/Cholombiano
Chonga: https://aesthetics.fandom.com/wiki/Chonga
Choni: https://aesthetics.fandom.com/wiki/Choni
Christian Girl Autumn: https://aesthetics.fandom.com/wiki/Christian_Girl_Autumn
Christmas: https://aesthetics.fandom.com/wiki/Christmas
Chromecore: https://aesthetics.fandom.com/wiki/Chromecore
Chunyu: https://aesthetics.fandom.com/wiki/Chunyu
Chuugoku Musume: https://aesthetics.fandom.com/wiki/Chuugoku_Musume
Cinnamon Girl: https://aesthetics.fandom.com/wiki/Cinnamon_Girl
City Pop: https://aesthetics.fandom.com/wiki/City_Pop
Classicism: https://aesthetics.fandom.com/wiki/Classicism
Classic Lolita: https://aesthetics.fandom.com/wiki/Classic_Lolita
Claymorphism: https://aesthetics.fandom.com/wiki/Claymorphism
Cleancore: https://aesthetics.fandom.com/wiki/Cleancore
Clean Girl: https://aesthetics.fandom.com/wiki/Clean_Girl
Clockpunk: https://aesthetics.fandom.com/wiki/Clockpunk
Clovercore: https://aesthetics.fandom.com/wiki/Clovercore
Clowncore: https://aesthetics.fandom.com/wiki/Clowncore
Club Kids: https://aesthetics.fandom.com/wiki/Club_Kids
Cluttercore: https://aesthetics.fandom.com/wiki/Cluttercore
Coastal Cowgirl: https://aesthetics.fandom.com/wiki/Coastal_Cowgirl
Coastal Grandmother: https://aesthetics.fandom.com/wiki/Coastal_Grandmother
Coastal Style: https://aesthetics.fandom.com/wiki/Coastal_Style
Cocalar: https://aesthetics.fandom.com/wiki/Cocalar
Coconut Girl: https://aesthetics.fandom.com/wiki/Coconut_Girl
Coffee House: https://aesthetics.fandom.com/wiki/Coffee_House
Communist Chic: https://aesthetics.fandom.com/wiki/Communist_Chic
Constructivism: https://aesthetics.fandom.com/wiki/Constructivism
Cool Britannia: https://aesthetics.fandom.com/wiki/Cool_Britannia
Coquette: https://aesthetics.fandom.com/wiki/Coquette
Colorful Pop: https://aesthetics.fandom.com/wiki/Colorful_Pop
Corporate: https://aesthetics.fandom.com/wiki/Corporate
Corporate Goth: https://aesthetics.fandom.com/wiki/Corporate_Goth
Corporate Grunge: https://aesthetics.fandom.com/wiki/Corporate_Grunge
Corporate Hippie: https://aesthetics.fandom.com/wiki/Corporate_Hippie
Corporate Memphis: https://aesthetics.fandom.com/wiki/Corporate_Memphis
Costumbrismo: https://aesthetics.fandom.com/wiki/Costumbrismo
Cottagecore: https://aesthetics.fandom.com/wiki/Cottagecore
Cottagegoth: https://aesthetics.fandom.com/wiki/Cottagegoth
Country: https://aesthetics.fandom.com/wiki/Country
Cozycore: https://aesthetics.fandom.com/wiki/Cozycore
Cozy Gamer: https://aesthetics.fandom.com/wiki/Cozy_Gamer
Craftcore: https://aesthetics.fandom.com/wiki/Craftcore
Crowcore: https://aesthetics.fandom.com/wiki/Crowcore
Crust Punk: https://aesthetics.fandom.com/wiki/Crust_Punk
Cryptidcore: https://aesthetics.fandom.com/wiki/Cryptidcore
Cubism: https://aesthetics.fandom.com/wiki/Cubism
Cult Party Kei: https://aesthetics.fandom.com/wiki/Cult_Party_Kei
Cumbiero: https://aesthetics.fandom.com/wiki/Cumbiero
Curly Girly: https://aesthetics.fandom.com/wiki/Curly_Girly
Cutecore: https://aesthetics.fandom.com/wiki/Cutecore
Cybercore: https://aesthetics.fandom.com/wiki/Cybercore
Cyberdelia: https://aesthetics.fandom.com/wiki/Cyberdelia
Cyber Doll: https://aesthetics.fandom.com/wiki/Cyber_Doll
Cyber Ghetto: https://aesthetics.fandom.com/wiki/Cyber_Ghetto
Cybergoth: https://aesthetics.fandom.com/wiki/Cybergoth
Cyber Grunge: https://aesthetics.fandom.com/wiki/Cyber_Grunge
Cyberminimalism: https://aesthetics.fandom.com/wiki/Cyberminimalism
Cyberpop: https://aesthetics.fandom.com/wiki/Cyberpop
Cyberprep: https://aesthetics.fandom.com/wiki/Cyberprep
Cyberpunk: https://aesthetics.fandom.com/wiki/Cyberpunk
Cybersigilism: https://aesthetics.fandom.com/wiki/Cybersigilism
Cyber Stylin’: https://aesthetics.fandom.com/wiki/Cyber_Stylin%E2%80%99
Cybertwee: https://aesthetics.fandom.com/wiki/Cybertwee
Czech Cubism: https://aesthetics.fandom.com/wiki/Czech_Cubism
Dadaism: https://aesthetics.fandom.com/wiki/Dadaism
Dadcore: https://aesthetics.fandom.com/wiki/Dadcore
Dandy: https://aesthetics.fandom.com/wiki/Dandy
Danish Golden Age: https://aesthetics.fandom.com/wiki/Danish_Golden_Age
Danish Pastel: https://aesthetics.fandom.com/wiki/Danish_Pastel
Dark Academia: https://aesthetics.fandom.com/wiki/Dark_Academia
Dark Aero: https://aesthetics.fandom.com/wiki/Dark_Aero
Dark Cabaret: https://aesthetics.fandom.com/wiki/Dark_Cabaret
Dark Fantasy: https://aesthetics.fandom.com/wiki/Dark_Fantasy
Dark Girly and Sweet Girly: https://aesthetics.fandom.com/wiki/Dark_Girly_and_Sweet_Girly
Dark Naturalism: https://aesthetics.fandom.com/wiki/Dark_Naturalism
Dark Nautical: https://aesthetics.fandom.com/wiki/Dark_Nautical
Dark Nymphet: https://aesthetics.fandom.com/wiki/Dark_Nymphet
Dark Romanticism: https://aesthetics.fandom.com/wiki/Dark_Romanticism
Darksynth: https://aesthetics.fandom.com/wiki/Darksynth
Dark Triad: https://aesthetics.fandom.com/wiki/Dark_Triad
Dau al Set: https://aesthetics.fandom.com/wiki/Dau_al_Set
Day Of The Dead: https://aesthetics.fandom.com/wiki/D%C3%ADa_De_Muertos
Dead Inside: https://aesthetics.fandom.com/wiki/Dead_Inside
Death Metal: https://aesthetics.fandom.com/wiki/Death_Metal
Deathrock: https://aesthetics.fandom.com/wiki/Deathrock
Decadence: https://aesthetics.fandom.com/wiki/Decadence
Deconstructivism: https://aesthetics.fandom.com/wiki/Deconstructivism
Decopunk: https://aesthetics.fandom.com/wiki/Decopunk
Decora: https://aesthetics.fandom.com/wiki/Decora
Deep Fried Meme: https://aesthetics.fandom.com/wiki/Deep_Fried_Meme
Dekotora: https://aesthetics.fandom.com/wiki/Dekotora
Delicate Sweet: https://aesthetics.fandom.com/wiki/Delicate_Sweet
Demoscene: https://aesthetics.fandom.com/wiki/Demoscene
Denpa: https://aesthetics.fandom.com/wiki/Denpa
De Stijl: https://aesthetics.fandom.com/wiki/De_Stijl
Devilcore: https://aesthetics.fandom.com/wiki/Devilcore
Dieselpunk: https://aesthetics.fandom.com/wiki/Dieselpunk
Digital Horror: https://aesthetics.fandom.com/wiki/Digital_Horror
Diner: https://aesthetics.fandom.com/wiki/Diner
Dionysism: https://aesthetics.fandom.com/wiki/Dionysism
Disco: https://aesthetics.fandom.com/wiki/Disco
Disco Deco: https://aesthetics.fandom.com/wiki/Disco_Deco
Disco Polo: https://aesthetics.fandom.com/wiki/Disco_Polo
Divine Machinery: https://aesthetics.fandom.com/wiki/Divine_Machinery
DIY Punk: https://aesthetics.fandom.com/wiki/DIY_Punk
Dizelaši: https://aesthetics.fandom.com/wiki/Dizela%C5%A1i
Dokukawaii: https://aesthetics.fandom.com/wiki/Dokukawaii
Dollar Store Vernacular: https://aesthetics.fandom.com/wiki/Dollar_Store_Vernacular
Dollcore: https://aesthetics.fandom.com/wiki/Dollcore
Dollette: https://aesthetics.fandom.com/wiki/Dollette
Dolly Girl: https://aesthetics.fandom.com/wiki/Dolly_Girl
Dolly Kei: https://aesthetics.fandom.com/wiki/Dolly_Kei
Doomer: https://aesthetics.fandom.com/wiki/Doomer
Dopamine Dressing: https://aesthetics.fandom.com/wiki/Dopamine_Dressing
DORFic: https://aesthetics.fandom.com/wiki/DORFic
Downtown Girl: https://aesthetics.fandom.com/wiki/Downtown_Girl
Dragoncore: https://aesthetics.fandom.com/wiki/Dragoncore
Draincore: https://aesthetics.fandom.com/wiki/Draincore
Dreamcore: https://aesthetics.fandom.com/wiki/Dreamcore

# Get All Aesthetics on Website

In [3]:
url = "https://aesthetics.fandom.com/wiki/List_of_Aesthetics"

# Create a cloudscraper instance to handle the request bypass
scraper = cloudscraper.create_scraper()
response = scraper.get(url)

if response.status_code == 200:
    html_content = response.text
    soup = BeautifulSoup(html_content, 'html.parser')

    # Replace 'your_class_name' with the actual class name you're looking for
    divs_with_links = soup.find_all('div', class_='twocolumn')

    all_links = []  # List to store links
    all_titles = []  # List to store titles

    for div_with_links in divs_with_links:
        # Find all <a> tags within each div
        links = div_with_links.find_all('a', href=True)

        # Extract and print the links and titles
        for link in links:
            href = link['href']
            title = link.get_text()  # Get the text within the <a> tag as the title

            all_links.append(href)
            all_titles.append(title)

else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")

dic = {}
dic['name'] = all_titles
dic['key'] = [l[6:] for l in all_links]
dic['link'] = ["https://aesthetics.fandom.com" + l for l in all_links]


table = pd.DataFrame(dic)
table

,name,key,link
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...
...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...

In [4]:
key = '2000s_Preppy'
link = table.loc[table['key'] == key,'link'].item()
content = requests.get(link)
content.text

'<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="content-security-policy" content="default-src &#39;none&#39;; script-src &#39;nonce-YUOLWC8YIQ3DQTA9PRlD1O&#39; &#39;unsafe-eval&#39; https://challenges.cloudflare.com; script-src-attr &#39;none&#39;; style-src &#39;unsafe-inline&#39;; img-src &#39;self&#39; https://challenges.cloudflare.com; connect-src &#39;self&#39; https://challenges.cloudflare.com; frame-src &#39;self&#39; https://challenges.cloudflare.com blob:; child-src &#39;self&#39; https://challenges.cloudflare.com blob:; worker-src blob:; form-action http: https:; base-uri &#39;self&#39;"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;padding-left:1.5rem;max-width:60rem}@media (width <= 720px){.main-content{margin-top:4rem}}#challenge-error-text{background-image:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+");background-repeat:no-repeat;background-size:contain;padding-left:34px}</style><meta http-equiv="refresh" content="360"></head><body><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script nonce="YUOLWC8YIQ3DQTA9PRlD1O">(function(){window._cf_chl_opt = {cFPWv: \'b\',cH: \'0jWEkHRWYn6yShkyKgWozOeUoqjfqB7b6apXYUSsxG4-1779892608-1.2.1.1-i6S09t9IsN6K8Oui9.kNqG5vq7yjgY336mQhRQBqSQjEH0QXLaCwjgXQw0hmhSEU\',cITimeS: \'1779892608\',cN: \'YUOLWC8YIQ3DQTA9PRlD1O\',cRay: \'a025c103191b134c\',cTplB: \'0\',cTplC:0,cTplO:0,cTplV:5,cType: \'managed\',cUPMDTk:"/wiki/2000s_Preppy?__cf_chl_tk=p5f6dKb3K7j.sQnrc98DUnNQj_l2jGcXb3es0hy.5Wg-1779892608-1.0.1.1-wTZcRvZ1ilUa1XE7laaocX9VyqQcsEo.KKQefAwFqEA",cvId: \'3\',cZone: \'aesthetics.fandom.com\',fa:"/wiki/2000s_Preppy?__cf_chl_f_tk=p5f6dKb3K7j.sQnrc98DUnNQj_l2jGcXb3es0hy.5Wg-1779892608-1.0.1.1-wTZcRvZ1ilUa1XE7laaocX9VyqQcsEo.KKQefAwFqEA",md: \'NFY3SfMzNzBxA6vV8Uu62.MDeB4BMdkej0eQzHta.b0-1779892608-1.2.1.1-CFjut8.9101fRJowMWd7Zy76xD8rtRj.YDqTgsqicnAfpxLL2WSFi7FGzhE695ld.8sBHahuGEcaI8ehKxorBcSfV1vvtysRjZ.qJb0JPE3VVwGTD.IG0RB5xuhHQbflP8m2Hpvh2o3FK5Otbi.MZmPspF_aV79FxJUBqs.9ub6oTI8RHkn6kR1yr4xIws5tSfIqsGpoQpz_DLx4YCuTkSk3FJV.AFkSh5tflPQxr72UgmPqScqmUXz1gvxBFCUVUiSljc7cFZdaRl32r7PrW7hQLsfQKwKfoawgvjCj5ZtBfI7GOsLdPbYvDXixrlHfpgNlcB35Gn5K7GwkYIyWK65za0iLvCTjPZ9Yg6k8TEtj8E_Q7cN7TkxwLgtOaK1nqznNIlbb1JXR8ZueDEZZmonUGO3OxQVdEADHWl7iMQJai13g.JoNRUwF9W6fTMpLwol2dDjY4oMWUk3yxwsX0cmU9_qTvv7VqYijGzgKugNwXxIICfUAT3afj2PSiwG17na1qcfOUo20FJox4_3S45RStpvags9vAUcHJXe8YQUlpcd7jxC9fjARxEuCD5_AJ_DotosmTqlgb4ywViq0oa8L3BsZj.5DtfT6sAaZ1sEZfzfRHjuzWtUcwHnMmbkXJ1tjMIr5_Dtrumom98WXj8rRGnEOEXvf0U05zRbOMV.qhv.kUzPdawowvjUgRZLWMsYczKWveUdzE92SsREDE4y_ZO1uR0Dler5tstom4c6.rk3X8fLd5NO.wzjnwAztOZ2FDrx2BHy8HQKyjJwIklRqdyVSnJm8Y0Jpzevhkscf0ihcg60jloq1Xi6EVqoOzqbTqM05HaGNzIwgg16_SUpmDvtIt4LmDI_K9bQh9.w010M8YI31eZAlSvkd5gPs5SFwjb8lEAA9pO54FhiQ2ZN4f5YoWAHAF5lRXH_jBXqb0BhgXzSKPvJrqNri0q1KwiUzNupUVlS_IqSrILV2CXqn67n.5d8B46F8AijWrh00WIL9touDoSx_WlVN8tmE0UWy_qnS6PhUyHJIdUrxeEphcNXlSEUAmNkWuI6GtGcwXTGCFl5S6XesV2arEUbR_0jmV63YL0J87Ph4WWdPmsZSJ8cJoQZIxErkgvs1mo0\',mdrd: \'7fcFakUnRm65bdTXkWK1BUbYvtslHpaQeqdcwW1L04c-1779892608-1.2.1.1-cmtbV6ZYlT03ClISmccCM8Rnmw6tPPWGer14MoqOp3iCgcn.0I2hz1ubGoz1VQqGxDU.0CSC_TyN_v8qGPiP3gFbyRTn4htfzp8886dPZcqad_uPEya8qA8xoUjuY0mUQi0_8_NrcObvHoLJGxxWEj.wm0PFt9nlzlFJ3_RabYaqXeOoN0QFmKx31p3x2WaA9u025DSvfz23VBuIdxn_2GY7f3np6P4QbUd_uCZBTtqp8kLo3KW_d8x7wfdLRykylLKiH0YfiF8OUNCahlaq.A\',};var a = document.createElement(\'script\');a.nonce = \'YUOLWC8YIQ3DQTA9PRlD1O\';a.src = \'/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=a025c103191b134c\';window._cf_chl_opt.cOgUHash = location.hash === \'\' && location.href.indexOf(\'#\') !== -1 ? \'#\' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === \'\' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf(\'?\') !== -1 ? \'?\' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null,"/wiki/2000s_Preppy?__cf_chl_rt_tk=p5f6dKb3K7j.sQnrc98DUnNQj_l2jGcXb3es0hy.5Wg-1779892608-1.0.1.1-wTZcRvZ1ilUa1XE7laaocX9VyqQcsEo.KKQefAwFqEA"+ window._cf_chl_opt.cOgUHash);a.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName(\'head\')[0].appendChild(a);}());</script></body></html>'

# Set up data collection

In [5]:
def extract_urls_from_url(url):
    # Create a cloudscraper instance to handle the request bypass
    scraper = cloudscraper.create_scraper()
    response = scraper.get(url)

    if response.status_code == 200:
        html_content = response.text
        soup = BeautifulSoup(html_content, 'html.parser')

        # Replace 'related_aesthetics' with the actual data source value you're looking for
        divs_with_data = soup.find_all('div', {'data-source': 'related_aesthetics'})

        if divs_with_data:
            # List to store extracted URLs
            url_list = []

            # Extract URLs from each div
            for div_with_data in divs_with_data:
                # Find all <a> tags within the div
                links = div_with_data.find_all('a', href=True)

                # Extract and append the href attribute to the list
                for link in links:
                    url_list.append(link['href'])

            return [l[6:] for l in url_list]
        else:
            print(f"{url[35:]}: Divs with data source 'related_aesthetics' not found.")
            return None

    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        return None

def get_colors(n):
    return ["#%06x" % random.randint(0, 0xFFFFFF) for _ in range(n)]

def extract_data_from_url(url):
    # Create a cloudscraper instance to handle the request bypass
    scraper = cloudscraper.create_scraper()
    response = scraper.get(url)

    if response.status_code == 200:
        html_content = response.text
        soup = BeautifulSoup(html_content, 'html.parser')

        # Data sources you're interested in
        data_sources = ['related_aesthetics', 'decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']

        # Dictionary to store extracted data
        extracted_data = {}
        
        no_get = ''
        
        for source in data_sources:
            divs_with_data = soup.find_all('div', {'data-source': source})

            if divs_with_data:
                # Lists to store extracted data for the current source
                urls = []
                text_data = []

                # Extract URLs or text from each div
                for div_with_data in divs_with_data:
                    if source == 'related_aesthetics':
                        # Extract URLs
                        links = div_with_data.find_all('a', href=True)
                        urls.extend(link['href'] for link in links)
                    else:
                        # Extract text
                        text = div_with_data.get_text(strip=True)
                        text_data.append(text)

                # Add the extracted data to the dictionary
                extracted_data[source] = (urls, text_data)

            else:
                no_get += f', {source}'
        if len(no_get) > 0:
            print(f"      {url[35:]}: {no_get[1:]} not found.")
        
        try:
            extracted_data['related_aesthetics'] = [l[6:] for l in extracted_data['related_aesthetics'][0]]
        except:
            extracted_data['related_aesthetics'] = []
        
        for d in ['decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']:
            try:
                extracted_data[d] = extracted_data[d][1][0][len(d):]
            except:
                extracted_data[d] = ""
        
        return extracted_data

    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")
        return None

# Download Date
last successfully downloaded on the 27/05/2026

In [6]:
extract_data = False #wiill download the data

if extract_data:
    data_check = ['related_aesthetics', 'decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']
    for d in data_check:
            dic[d] = []


    counter = 0
    for l in dic['link']:
        result = extract_data_from_url(l)
        for d in data_check:
            dic[d] += [result[d]]
        if counter % 100 == 0 :
            print("")
            print(round(counter/1000,4)*100.,"% complete")
            print("")
        counter += 1

    dic_play = {}
    for d in ['name', 'key', 'link', 'related_aesthetics', 'decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']:
        dic_play[d] = dic[d] 
        print(d,": ",len(dic[d]))

    table = pd.DataFrame(dic_play)
    table.to_csv('Aesthetic network.csv', index=False)

table = pd.read_csv("Aesthetic network.csv")
table['related_aesthetics'] = table['related_aesthetics'].apply(ast.literal_eval)
table

,name,key,link,related_aesthetics,decade_of_origin,key_motifs,key_colours,key_values,related_media,earliest_origin,latest_origin
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone,"[Mod, New_Wave, Northern_Soul, Punk, Reggae, R...",Late 1970s,"Checkerboard pattern, suits, pork pie hats, lo...",Black and white,"Anti-racism, racial unity, working-class pride...",NaN,1970.0,1970.0
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...,"[Baroque, Curly_Girly, McBling, Parisian_Girly...",2000s,"Ornate details, gilded accents, sumptuous fabr...","Black and gold, but also a broader range inclu...","Opulence, drama, a reinterpretation of traditi...",NaN,2000.0,2000.0
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy,"[Barbiecore, Basic_Girl, Boujee, Bubblegum_Bit...",2000s,"Wealth, popularity, femininity, elitism","Light and bright colors, a lot of pink, black ...",NaN,"lueless, Gossip Girl",2000.0,2000.0
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom,[],"Late 90's, Early 2000's","Yoga mats, suburban SUVs, large tote bags, the...","Black, white, light gray, beige, sage green, p...","Disciplined wellness, balance between motherho...",NaN,1990.0,2000.0
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...,"[2010s_Soft_Kawaii, 2010s_Meme_Maximalism, Pas...",2010s,"Anime, arcades, mascots, school uniforms",Bright pastels,NaN,NaN,2010.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style,"[Art_Nouveau, Arts_and_Crafts_Movement, Romant...",1890s-1910s,"Sunrays, floral carving, Goral motifs, hearts","Wood tones, stone grey, green","Goral culture, national identity, connection w...",NaN,1890.0,1910.0
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou,"[Bikiniarze, Stilyagi, Swingjugend, Teddy_Boys]",1940s,"Oversized jackets, narrow trousers, long hair,...","Black, white, often bright or checkered patter...","Individualism, nonconformity, defiance, hedoni...",NaN,1940.0,1940.0
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef,"[Chav, Hipness_Purgatory, Juggalo, Kitsch, McB...",2000s,"DIY fashion, kitsch, customized cars, gold jew...",NaN,"Reclaiming stereotypes, unapologetic attitude,...",NaN,2000.0,2000.0
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism,"[Constructivism, Cubism, Dadaism, Expressionis...",1921–1926,"The ""Barbarogenius,"" machines, the modern city...","Often black, white, and red","Anti-traditionalism, Balkan cultural revival, ...",NaN,1921.0,1926.0
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...,"[Grunge, Horror_Punk, Post-Apocalyptic]",1960s,"Meat, torn clothes, empty cities, post-apocaly...","Faded and dull colors, reds, greens, purples, ...","Fatigue, hunger, survival",NaN,1960.0,1960.0

In [7]:
extract_data = False # will download the data

if extract_data:
    data_check = ['related_aesthetics', 'decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']
    for d in data_check:
        dic[d] = []

    counter = 0
    for l in dic['link']:
        
        # This flag keeps track of whether we successfully grabbed the data for the current link
        success = False
        
        while not success:
            try:
                result = extract_data_from_url(l)
                
                # If cloudscraper gets blocked, result becomes None, which triggers the 'except' block below
                if result is None:
                    raise Exception("Page retrieval failed (likely hit a 403 block).")
                
                # If we have data, append it normally
                for d in data_check:
                    dic[d] += [result[d]]
                
                success = True # Break out of the while loop to move to the next URL
                
            except Exception as e:
                print(f"\n⚠️ Error encountered on {l[35:]}: {e}")
                print("Waiting 20 seconds before retrying...")
                time.sleep(2) # Pauses for a few seconds before trying the exact same URL again
        
        if counter % 100 == 0 :
            print("")
            print(round(counter/1000,4)*100.,"% complete")
            print("")
        counter += 1

    dic_play = {}
    for d in ['name', 'key', 'link', 'related_aesthetics', 'decade_of_origin', 'key_motifs', 'key_colours', 'key_values', 'related_media']:
        dic_play[d] = dic[d] 
        print(d,": ",len(dic[d]))

    table = pd.DataFrame(dic_play)
    table.to_csv('Aesthetic network.csv', index=False)

table = pd.read_csv("Aesthetic network.csv")
table['related_aesthetics'] = table['related_aesthetics'].apply(ast.literal_eval)
table

,name,key,link,related_aesthetics,decade_of_origin,key_motifs,key_colours,key_values,related_media,earliest_origin,latest_origin
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone,"[Mod, New_Wave, Northern_Soul, Punk, Reggae, R...",Late 1970s,"Checkerboard pattern, suits, pork pie hats, lo...",Black and white,"Anti-racism, racial unity, working-class pride...",NaN,1970.0,1970.0
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...,"[Baroque, Curly_Girly, McBling, Parisian_Girly...",2000s,"Ornate details, gilded accents, sumptuous fabr...","Black and gold, but also a broader range inclu...","Opulence, drama, a reinterpretation of traditi...",NaN,2000.0,2000.0
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy,"[Barbiecore, Basic_Girl, Boujee, Bubblegum_Bit...",2000s,"Wealth, popularity, femininity, elitism","Light and bright colors, a lot of pink, black ...",NaN,"lueless, Gossip Girl",2000.0,2000.0
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom,[],"Late 90's, Early 2000's","Yoga mats, suburban SUVs, large tote bags, the...","Black, white, light gray, beige, sage green, p...","Disciplined wellness, balance between motherho...",NaN,1990.0,2000.0
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...,"[2010s_Soft_Kawaii, 2010s_Meme_Maximalism, Pas...",2010s,"Anime, arcades, mascots, school uniforms",Bright pastels,NaN,NaN,2010.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style,"[Art_Nouveau, Arts_and_Crafts_Movement, Romant...",1890s-1910s,"Sunrays, floral carving, Goral motifs, hearts","Wood tones, stone grey, green","Goral culture, national identity, connection w...",NaN,1890.0,1910.0
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou,"[Bikiniarze, Stilyagi, Swingjugend, Teddy_Boys]",1940s,"Oversized jackets, narrow trousers, long hair,...","Black, white, often bright or checkered patter...","Individualism, nonconformity, defiance, hedoni...",NaN,1940.0,1940.0
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef,"[Chav, Hipness_Purgatory, Juggalo, Kitsch, McB...",2000s,"DIY fashion, kitsch, customized cars, gold jew...",NaN,"Reclaiming stereotypes, unapologetic attitude,...",NaN,2000.0,2000.0
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism,"[Constructivism, Cubism, Dadaism, Expressionis...",1921–1926,"The ""Barbarogenius,"" machines, the modern city...","Often black, white, and red","Anti-traditionalism, Balkan cultural revival, ...",NaN,1921.0,1926.0
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...,"[Grunge, Horror_Punk, Post-Apocalyptic]",1960s,"Meat, torn clothes, empty cities, post-apocaly...","Faded and dull colors, reds, greens, purples, ...","Fatigue, hunger, survival",NaN,1960.0,1960.0

In [8]:
table

,name,key,link,related_aesthetics,decade_of_origin,key_motifs,key_colours,key_values,related_media,earliest_origin,latest_origin
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone,"[Mod, New_Wave, Northern_Soul, Punk, Reggae, R...",Late 1970s,"Checkerboard pattern, suits, pork pie hats, lo...",Black and white,"Anti-racism, racial unity, working-class pride...",NaN,1970.0,1970.0
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...,"[Baroque, Curly_Girly, McBling, Parisian_Girly...",2000s,"Ornate details, gilded accents, sumptuous fabr...","Black and gold, but also a broader range inclu...","Opulence, drama, a reinterpretation of traditi...",NaN,2000.0,2000.0
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy,"[Barbiecore, Basic_Girl, Boujee, Bubblegum_Bit...",2000s,"Wealth, popularity, femininity, elitism","Light and bright colors, a lot of pink, black ...",NaN,"lueless, Gossip Girl",2000.0,2000.0
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom,[],"Late 90's, Early 2000's","Yoga mats, suburban SUVs, large tote bags, the...","Black, white, light gray, beige, sage green, p...","Disciplined wellness, balance between motherho...",NaN,1990.0,2000.0
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...,"[2010s_Soft_Kawaii, 2010s_Meme_Maximalism, Pas...",2010s,"Anime, arcades, mascots, school uniforms",Bright pastels,NaN,NaN,2010.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style,"[Art_Nouveau, Arts_and_Crafts_Movement, Romant...",1890s-1910s,"Sunrays, floral carving, Goral motifs, hearts","Wood tones, stone grey, green","Goral culture, national identity, connection w...",NaN,1890.0,1910.0
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou,"[Bikiniarze, Stilyagi, Swingjugend, Teddy_Boys]",1940s,"Oversized jackets, narrow trousers, long hair,...","Black, white, often bright or checkered patter...","Individualism, nonconformity, defiance, hedoni...",NaN,1940.0,1940.0
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef,"[Chav, Hipness_Purgatory, Juggalo, Kitsch, McB...",2000s,"DIY fashion, kitsch, customized cars, gold jew...",NaN,"Reclaiming stereotypes, unapologetic attitude,...",NaN,2000.0,2000.0
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism,"[Constructivism, Cubism, Dadaism, Expressionis...",1921–1926,"The ""Barbarogenius,"" machines, the modern city...","Often black, white, and red","Anti-traditionalism, Balkan cultural revival, ...",NaN,1921.0,1926.0
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...,"[Grunge, Horror_Punk, Post-Apocalyptic]",1960s,"Meat, torn clothes, empty cities, post-apocaly...","Faded and dull colors, reds, greens, purples, ...","Fatigue, hunger, survival",NaN,1960.0,1960.0

# Clean Data

In [12]:
# Function to clean the column and extract the smallest number, converting shorthand decades
def clean_to_number(text):
    # Regular expression to find all numbers
    numbers = re.findall(r'\d+', text)
    
    # Check for shorthand decade formats like '90s' and convert to full year format
    if re.search(r'\b\d{1,2}s\b', text):
        # Extract the number part (like 90 in '90s')
        shorthand_decade = re.search(r'\d{1,2}', text).group()
        # Convert to full decade (e.g., 90 -> 1990, 80 -> 1980)
        full_decade = int(shorthand_decade) + (1900 if int(shorthand_decade) < 100 else 0)
        return full_decade
    
    if numbers:
        # Convert found numbers to integers and return the smallest one
        return min(map(int, numbers))
    else:
        # If no numbers found, return None
        return None
        
# Convert all entries in 'decade_of_origin' to strings
table['decade_of_origin'] = table['decade_of_origin'].astype(str)
# Apply the function to clean the 'decade_of_origin' column
table['earliest_origin'] = table['decade_of_origin'].apply(clean_to_number)

key_adj = ['Cottagecore', 'Aestheticism', 'Afropunk', 'American_Gothic', 'Ancient_Egypt', 'Arabian_Nights', 'Art_Deco', 'Australian_Outback', 'Baroque', 'Burlesque', 'Cassette_Futurism', 'Classicism', 'Clockpunk', 'Dionysism', 'Driftcore', 'Expressionism', 'Fanfare', 'Flamenco', 'French_Provincial_Style', 'Gangsta_Rap', 'Goofcore', 'Gothic', 'Hair_Metal', 'Italian_Renaissance', 'Kiwiana', 'Maximalism', 'Medieval', 'Modernism', 'Mud%C3%A9jar', 'Neo_Baroque', 'Post-Apocalyptic', 'Rangercore', 'Rebel_Academia', 'Rustic', 'Saint_Patrick%27s_Day', 'Scrapbook', 'Southern_Gothic', 'Spanish_Golden_Age', 'Spy_Fiction', 'Steampunk', 'Teslapunk', 'Tranquil_Spa_Graphics', 'Tuscan_Rustic', 'Vampire', 'Viking', 'Werewolf']
year_adj = [2010, 1900, 1980, 1850, -30, 1850, 1910, 0, 1750, 1700, 1970, -500, 1500, -500, 1995, 1900, 1800, 1400,1600, 1980, 1980, 1100, 1980, 1650, 1950, 1850, 400, 1900, 1500, 1980, 1800, 2019, 1950, 1800, 900, 1500, 1800, 1600, 1900, 1980, 2000, 400, 1975, 1800, 700, 1910]

for i in range(len(key_adj)):
    table.loc[table['key'] == key_adj[i],'earliest_origin'] = year_adj[i]

table.to_csv('Aesthetic network.csv', index=False)
table

,name,key,link,related_aesthetics,decade_of_origin,key_motifs,key_colours,key_values,related_media,earliest_origin
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone,"[Mod, New_Wave, Northern_Soul, Punk, Reggae, R...",Late 1970s,"Checkerboard pattern, suits, pork pie hats, lo...",Black and white,"Anti-racism, racial unity, working-class pride...",NaN,1970.0
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...,"[Baroque, Curly_Girly, McBling, Parisian_Girly...",2000s,"Ornate details, gilded accents, sumptuous fabr...","Black and gold, but also a broader range inclu...","Opulence, drama, a reinterpretation of traditi...",NaN,2000.0
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy,"[Barbiecore, Basic_Girl, Boujee, Bubblegum_Bit...",2000s,"Wealth, popularity, femininity, elitism","Light and bright colors, a lot of pink, black ...",NaN,"lueless, Gossip Girl",2000.0
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom,[],"Late 90's, Early 2000's","Yoga mats, suburban SUVs, large tote bags, the...","Black, white, light gray, beige, sage green, p...","Disciplined wellness, balance between motherho...",NaN,90.0
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...,"[2010s_Soft_Kawaii, 2010s_Meme_Maximalism, Pas...",2010s,"Anime, arcades, mascots, school uniforms",Bright pastels,NaN,NaN,2010.0
...,...,...,...,...,...,...,...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style,"[Art_Nouveau, Arts_and_Crafts_Movement, Romant...",1890s-1910s,"Sunrays, floral carving, Goral motifs, hearts","Wood tones, stone grey, green","Goral culture, national identity, connection w...",NaN,1890.0
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou,"[Bikiniarze, Stilyagi, Swingjugend, Teddy_Boys]",1940s,"Oversized jackets, narrow trousers, long hair,...","Black, white, often bright or checkered patter...","Individualism, nonconformity, defiance, hedoni...",NaN,1940.0
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef,"[Chav, Hipness_Purgatory, Juggalo, Kitsch, McB...",2000s,"DIY fashion, kitsch, customized cars, gold jew...",NaN,"Reclaiming stereotypes, unapologetic attitude,...",NaN,2000.0
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism,"[Constructivism, Cubism, Dadaism, Expressionis...",1921–1926,"The ""Barbarogenius,"" machines, the modern city...","Often black, white, and red","Anti-traditionalism, Balkan cultural revival, ...",NaN,1921.0
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...,"[Grunge, Horror_Punk, Post-Apocalyptic]",1960s,"Meat, torn clothes, empty cities, post-apocaly...","Faded and dull colors, reds, greens, purples, ...","Fatigue, hunger, survival",NaN,1960.0

In [9]:
# Helper function to find and parse ALL years/decades inside the text
def parse_all_years(text):
    text = str(text).strip().lower()
    if not text or text == 'nan':
        return []
    
    found_years = []

    # Standardize all dashes right away (including box lines like ─)
    text = re.sub(r'[–—−─]', '-', text)

    # 1. Handle Century Ranges and Single Centuries (e.g., "14th-16th centuries", "19th century")
    century_matches = re.findall(r'(\d{1,2})(?:st|nd|rd|th)?(?:\s*-\s*(\d{1,2})(?:st|nd|rd|th)?)?\s+centur', text)
    if century_matches:
        for c1, c2 in century_matches:
            if c1:
                v1 = int(c1)
                found_years.extend([(v1 - 1) * 100, v1 * 100])
            if c2:
                v2 = int(c2)
                found_years.extend([(v2 - 1) * 100, v2 * 100])
        # FIX: Erase the century wording from the text so it doesn't interfere with standard number parsing
        text = re.sub(r'\d{1,2}(?:st|nd|rd|th)?(?:\s*-\s*\d{1,2}(?:st|nd|rd|th)?)?\s+centur\w*', '', text)

    # 2. Find shorthand chunks (e.g., 90's, 90s, 00's, 2000's)
    shorthands = re.findall(r'(\d{1,4})\'?s', text)
    for item in shorthands:
        val = int(item)
        if val < 100:  
            # Cut-off rule: < 20 means 2000s, >= 20 means 1900s
            full_decade = val + (2000 if val < 20 else 1900)
            found_years.append(full_decade)
        else:  
            found_years.append(val)
            
    # 3. Find standalone numbers
    # Strip away the shorthands we already evaluated to prevent double-counting
    clean_text = re.sub(r'\d{1,4}\'?s', '', text)
    
    # Check if the text explicitly states BC or BCE
    is_bc = 'bc' in clean_text or 'bce' in clean_text

    standalone_numbers = re.findall(r'\d+', clean_text)
    for item in standalone_numbers:
        val = int(item)
        # Only turn it negative if it's explicitly a BC/BCE date
        if is_bc:
            val = -abs(val)
        found_years.append(val)
        
    return found_years

# Function to extract the smallest calculated year
def clean_to_earliest(text):
    years = parse_all_years(text)
    return min(years) if years else None

# Function to extract the largest calculated year
def clean_to_latest(text):
    years = parse_all_years(text)
    return max(years) if years else None

# Convert all entries in 'decade_of_origin' to strings
table['decade_of_origin'] = table['decade_of_origin'].astype(str)

# Apply the functions to clean the columns
table['earliest_origin'] = table['decade_of_origin'].apply(clean_to_earliest)
table['latest_origin'] = table['decade_of_origin'].apply(clean_to_latest)

# Hardcoded adjustments
manual_adjustments = {
    'Cottagecore': 2010,                        # "2010s (inspired by the 19th century)" -> Modern internet era
    'Aestheticism': (1860, 1900),               # "Late-19th century (approximately 1860s-1900s)"
    'Afropunk': (1970, 2000),                   # "1970s (origins)2000s (wider popularization)"
    'American_Gothic': 1850,                    # Flatten historic baseline
    'Ancient_Egypt': (-3150, -30),               # "3150 BC─30 BC" -> True chronological bounds
    'Arabian_Nights': 2020,                     # Modern interpretation decade tracking
    'Art_Deco': (1910, 1930),                   # "1910s–1930s"
    'Australian_Outback': 1900,                  # Approximate historical tracking match
    'Baroque': (1600, 1750),                    # "c. 1600 - 1750"
    'Burlesque': (1600, 1700),                  # "17th Century"
    'Cassette_Futurism': 1970,                  # "1970s"
    'Classicism': (-500, -400),                 # "5th century BCE (Original Period)" -> Correctly negative
    'Clockpunk': (1300, 1600),                  # "Renaissance inspiration (14th–17th centuries)" -> century start bounds
    'Dionysism': (-1200, -600),                 # "13th-7th centuries BC" -> Correct BC ranges
    'Driftcore': 1995,                          # Fixed alignment
    'Expressionism': (1900, 1920),              # "1900s-1920s"
    'Fanfare': (1742, 1900),                    # "Created 1742, popularized late 19th century"
    'Flamenco': (1700, 1800),                   # "Late 18th century (modern-day form)"
    'French_Provincial_Style': (1600, 1800),    # "17th-18th Century"
    'Gangsta_Rap': 1980,                        # Standard 80s baseline 
    'Goofcore': 1980,                           # 80s movement baseline
    'Gothic': (1700, 1800),                     # "Late 18th century (c. 1764)"
    'Hair_Metal': (1970, 1980),                 # "Late 70's-early 80's"
    'Italian_Renaissance': (1300, 1600),        # "14th-16th Centuries"
    'Kiwiana': (1900, 2000),                    # "Around the middle of the 20th century"
    'Maximalism': (1800, 1900),                 # "19th Century"
    'Medieval': (400, 500),                     # "5th Century AD"
    'Modernism': 1900,                          # Standard 20th-century baseline
    'Mud%C3%A9jar': (1100, 1600),               # "12th–16th Centuries"
    'Neo_Baroque': 1980,                        # Modern styling revival
    'Post-Apocalyptic': (1800, 1900),           # "Biblical stories, 19th Century works"
    'Rangercore': 2019,                         # Internet subculture arrival
    'Rebel_Academia': 1950,                     # Mid-century stylistic backdrop
    'Rustic': 1800,                             # Fallback for completely empty/NaN row
    'Saint_Patrick%27s_Day': 900,               # Legacy cultural mapping
    'Scrapbook': 1500,                          # Historical artifact alignment
    'Southern_Gothic': (1800, 1900),            # "19th Century"
    'Spanish_Golden_Age': (1492, 1681),         # "c. 1492 - 1681"
    'Spy_Fiction': (1800, 1900),                # "19th century"
    'Steampunk': (1960, 2010),                  # "1960s (aesthetic)1980s (term)2000s/2010s"
    'Teslapunk': 2000,                          # "2000s19th century (concept)" -> Modern aesthetic timeline
    'Tranquil_Spa_Graphics': 2000,              # Y2K corporate aesthetic grouping
    'Tuscan_Rustic': 2000,                      # "Traditional, popularized in the mid-2000s"
    'Vampire': (1800, 1900),                    # "19th Century (Modern Archetype)"
    'Viking': 700,                              # Historic baseline bounds
    'Werewolf': (1910, 1910)                    # Skip ancient legend text noise to target modern aesthetic trope
}

for key, adj_val in manual_adjustments.items():
    if isinstance(adj_val, tuple):
        table.loc[table['key'] == key, 'earliest_origin'] = adj_val[0]
        table.loc[table['key'] == key, 'latest_origin'] = adj_val[1]
    else:
        table.loc[table['key'] == key, 'earliest_origin'] = adj_val
        table.loc[table['key'] == key, 'latest_origin'] = adj_val

table.to_csv('Aesthetic network.csv', index=False)
table

,name,key,link,related_aesthetics,decade_of_origin,key_motifs,key_colours,key_values,related_media,earliest_origin,latest_origin
0,2 Tone,2_Tone,https://aesthetics.fandom.com/wiki/2_Tone,"[Mod, New_Wave, Northern_Soul, Punk, Reggae, R...",Late 1970s,"Checkerboard pattern, suits, pork pie hats, lo...",Black and white,"Anti-racism, racial unity, working-class pride...",NaN,1970.0,1970.0
1,2000s Modern Baroque,2000s_Modern_Baroque,https://aesthetics.fandom.com/wiki/2000s_Moder...,"[Baroque, Curly_Girly, McBling, Parisian_Girly...",2000s,"Ornate details, gilded accents, sumptuous fabr...","Black and gold, but also a broader range inclu...","Opulence, drama, a reinterpretation of traditi...",NaN,2000.0,2000.0
2,2000s Preppy,2000s_Preppy,https://aesthetics.fandom.com/wiki/2000s_Preppy,"[Barbiecore, Basic_Girl, Boujee, Bubblegum_Bit...",2000s,"Wealth, popularity, femininity, elitism","Light and bright colors, a lot of pink, black ...",NaN,"lueless, Gossip Girl",2000.0,2000.0
3,2000s Yoga Mom,2000s_Yoga_Mom,https://aesthetics.fandom.com/wiki/2000s_Yoga_Mom,[],"Late 90's, Early 2000's","Yoga mats, suburban SUVs, large tote bags, the...","Black, white, light gray, beige, sage green, p...","Disciplined wellness, balance between motherho...",NaN,1990.0,2000.0
4,2010s Bright Kawaii,2010s_Bright_Kawaii,https://aesthetics.fandom.com/wiki/2010s_Brigh...,"[2010s_Soft_Kawaii, 2010s_Meme_Maximalism, Pas...",2010s,"Anime, arcades, mascots, school uniforms",Bright pastels,NaN,NaN,2010.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...
1052,Zakopane Style,Zakopane_Style,https://aesthetics.fandom.com/wiki/Zakopane_Style,"[Art_Nouveau, Arts_and_Crafts_Movement, Romant...",1890s-1910s,"Sunrays, floral carving, Goral motifs, hearts","Wood tones, stone grey, green","Goral culture, national identity, connection w...",NaN,1890.0,1910.0
1053,Zazou,Zazou,https://aesthetics.fandom.com/wiki/Zazou,"[Bikiniarze, Stilyagi, Swingjugend, Teddy_Boys]",1940s,"Oversized jackets, narrow trousers, long hair,...","Black, white, often bright or checkered patter...","Individualism, nonconformity, defiance, hedoni...",NaN,1940.0,1940.0
1054,Zef,Zef,https://aesthetics.fandom.com/wiki/Zef,"[Chav, Hipness_Purgatory, Juggalo, Kitsch, McB...",2000s,"DIY fashion, kitsch, customized cars, gold jew...",NaN,"Reclaiming stereotypes, unapologetic attitude,...",NaN,2000.0,2000.0
1055,Zenitism,Zenitism,https://aesthetics.fandom.com/wiki/Zenitism,"[Constructivism, Cubism, Dadaism, Expressionis...",1921–1926,"The ""Barbarogenius,"" machines, the modern city...","Often black, white, and red","Anti-traditionalism, Balkan cultural revival, ...",NaN,1921.0,1926.0
1056,Zombie Apocalypse,Zombie_Apocalypse,https://aesthetics.fandom.com/wiki/Zombie_Apoc...,"[Grunge, Horror_Punk, Post-Apocalyptic]",1960s,"Meat, torn clothes, empty cities, post-apocaly...","Faded and dull colors, reds, greens, purples, ...","Fatigue, hunger, survival",NaN,1960.0,1960.0